set number
set relativenumber
set history=1000
set mouse=a
set autoread
set ruler
set hlsearch
set incsearch
set showmatch
set encoding=utf-8
set fileencodings=utf-8,cp949
set shiftwidth=4
set expandtab
set tabstop=4
set listchars=tab:>·,trail:␣,extends:>,precedes:<
set list
set nowrap
set signcolumn=yes
set clipboard=unnamedplus
