vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.history = 1000
vim.opt.mouse = 'a'
vim.opt.ruler = true
vim.opt.hlsearch = true
vim.opt.incsearch = true
vim.opt.showmatch = true
vim.opt.encoding = 'utf-8'
vim.opt.fileencodings = 'utf-8,cp949'
vim.opt.expandtab = true
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.listchars = 'tab:>·,trail:␣,extends:>,precedes:<'
vim.opt.list = true
vim.opt.wrap = false
vim.opt.signcolumn = 'yes'
vim.opt.clipboard = 'unnamedplus'
vim.opt.autoread = true
vim.opt.swapfile = false
vim.opt.winborder = "rounded"
vim.cmd('syntax on')
vim.cmd('set completeopt+=noselect')
