# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing
exec-once = [workspace 1 silent] kitty -- tmux new-session -A -s main
exec-once = [workspace 2 silent] zen-browser
exec-once = [workspace 3 silent] obsidian
exec-once = [workspace 4 silent] webcord
exec-once = [workspace 10 silent] zen-browser --profile ~/.zen/*.AIGPT --kiosk
exec-once = [workspace special:youtube silent] kitty --hold sh -c 'kitty @ launch --location=vsplit cava ; kitty @ resize-window --axis vertical --increment -20 ; yt'
exec-once = [workspace special:todo silent] ~/Applications/Todoist-linux-9.18.0-x86_64-latest_fad94a6d4d75d81c5d2a637648255c13.AppImage
