# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/
monitor = DP-3, 2560x1440@164.96, 0x0, 1
monitor = HDMI-A-1, 2560x1440@60, 2560x0, 1

device {
    name = logitech-g304-1
    sensitivity = -0.45
}
