# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/
# monitor = DP-2, 2560x1440@164.96, 0x0, 1
# monitor = HDMI-A-1, 2560x1440, 2560x0, 1
monitor = , preferred, auto, 1
device {
    name = logitech-g304-1
    sensitivity = -0.45
}

general {
    # Gaps and border
    gaps_in = 4
    gaps_out = 5
    gaps_workspaces = 50

    border_size = 1
    col.active_border = rgba(0DB7D455)
    col.inactive_border = rgba(31313600)
    resize_on_border = true

    no_focus_fallback = true

    allow_tearing = true # This just allows the `immediate` window rule to work

    snap {
        enabled = true
        window_gap = 4
        monitor_gap = 5
        respect_gaps = true
    }
}

input {
    ...
    repeat_delay = 300
    repeat_rate = 100
}
