# See https://wiki.hyprland.org/Configuring/Binds/
#!
##! User
bind = Ctrl+Super, Slash, exec, xdg-open ~/.config/illogical-impulse/config.json # Edit shell config
bind = Ctrl+Super+Alt, Slash, exec, xdg-open ~/.config/hypr/custom/keybinds.conf # Edit extra keybinds

# Add stuff here
# Use #! to add an extra column on the cheatsheet
# Use ##! to add a section in that column
# Add a comment after a bind to add a description, like above

bind = Super, RETURN, exec, $terminal
bind = Super, Q, killactive,
bind = Super, M, exit,
bind = Super, V, togglefloating,
bind = Super, S, togglesplit, # dwindle

# Move focus with mainMod + arrow keys
bind = Super, H, movefocus, l
bind = Super, L, movefocus, r
bind = Super, K, movefocus, u
bind = Super, J, movefocus, d

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = Super SHIFT, 1, movetoworkspacesilent, 1
bind = Super SHIFT, 2, movetoworkspacesilent, 2
bind = Super SHIFT, 3, movetoworkspacesilent, 3
bind = Super SHIFT, 4, movetoworkspacesilent, 4
bind = Super SHIFT, 5, movetoworkspacesilent, 5
bind = Super SHIFT, 6, movetoworkspacesilent, 6
bind = Super SHIFT, 7, movetoworkspacesilent, 7
bind = Super SHIFT, 8, movetoworkspacesilent, 8
bind = Super SHIFT, 9, movetoworkspacesilent, 9
bind = Super SHIFT, 0, movetoworkspacesilent, 10
bind = Super, Right, movewindow, r
bind = Super, Left,  movewindow, l
bind = Super, Up,  movewindow, u
bind = Super, Down,  movewindow, d

bind = Super, Y, togglespecialworkspace, youtube
bind = Super SHIFT, Y, movetoworkspacesilent, special:youtube
bind = Super, T, togglespecialworkspace, todo
bind = Super SHIFT, T, movetoworkspacesilent, special:todo
bind = Super, P, togglespecialworkspace, temp
bind = Super SHIFT, P, movetoworkspacesilent, special:temp
