# See https://wiki.hyprland.org/Configuring/Binds/
#!
unbind = Super, B
unbind = Super, K
unbind = Super, J
unbind = Super, Left
unbind = Super, Right
unbind = Super, Up
unbind = Super, Down
unbind = Super+Shift, Left
unbind = Super+Shift, Right
unbind = Super+Shift, Up
unbind = Super+Shift, Down
unbind = Super+Alt, 1
unbind = Super+Alt, 2
unbind = Super+Alt, 3
unbind = Super+Alt, 4
unbind = Super+Alt, 5
unbind = Super+Alt, 6
unbind = Super+Alt, 7
unbind = Super+Alt, 8
unbind = Super+Alt, 9
unbind = Super+Alt, 0
unbind = Super+Alt, S
unbind = Ctrl+Super, S
unbind = Super, T
unbind = Ctrl+Alt, T
unbind = Super, W
unbind = Super, L
unbind = Super+Shift, L

##! Configuration
bind = Ctrl+Super, Slash, exec, xdg-open ~/.config/illogical-impulse/config.json # Edit shell config
bind = Ctrl+Super+Alt, Slash, exec, xdg-open ~/.config/hypr/custom/keybinds.conf # Edit extra keybinds

##! Screen
bind = Ctrl Shift, Left, movecurrentworkspacetomonitor, l # Move current workspace to left monitor
bind = Ctrl Shift, Right, movecurrentworkspacetomonitor, r # Move current workspace to right monitor

# Idle
bindd = Super+Shift, L, Lock, exec, loginctl lock-session # Lock

# Add stuff here
# Use #! to add an extra column on the cheatsheet
# Use ##! to add a section in that column
# Add a comment after a bind to add a description, like above

##! Apps
bind = Super, RETURN, exec, $terminal # Terminal
bind = Super, B, exec, ~/.config/hypr/hyprland/scripts/launch_first_available.sh "zen-browser" "google-chrome-stable" "firefox" "brave" "chromium" "microsoft-edge-stable" "opera" "librewolf" # Browser
bind = Super, Q, killactive
bind = Super, M, exit # Exit

##! Window
bind = Super, V, togglefloating
bind = Super, S, togglesplit # dwindle
bind = Super, H, movefocus, l
bind = Super, L, movefocus, r
bind = Super, K, movefocus, u
bind = Super, J, movefocus, d
bind = Super, Right, movewindow, r
bind = Super, Left,  movewindow, l
bind = Super, Up,  movewindow, u
bind = Super, Down,  movewindow, d

##! Workspace
bind = Super, code:10, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh workspace 1 # [hidden]
bind = Super, code:11, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh workspace 2 # [hidden]
bind = Super, code:12, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh workspace 3 # [hidden]
bind = Super, code:13, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh workspace 4 # [hidden]
bind = Super, code:14, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh workspace 5 # [hidden]
bind = Super, code:15, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh workspace 6 # [hidden]
bind = Super, code:16, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh workspace 7 # [hidden]
bind = Super, code:17, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh workspace 8 # [hidden]
bind = Super, code:18, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh workspace 9 # [hidden]
bind = Super, code:19, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh workspace 10 # [hidden]
bind = Super SHIFT, 1, movetoworkspacesilent, 1
bind = Super SHIFT, 2, movetoworkspacesilent, 2
bind = Super SHIFT, 3, movetoworkspacesilent, 3
bind = Super SHIFT, 4, movetoworkspacesilent, 4
bind = Super SHIFT, 5, movetoworkspacesilent, 5
bind = Super SHIFT, 6, movetoworkspacesilent, 6
bind = Super SHIFT, 7, movetoworkspacesilent, 7
bind = Super SHIFT, 8, movetoworkspacesilent, 8
bind = Super SHIFT, 9, movetoworkspacesilent, 9
bind = Super SHIFT, 0, movetoworkspacesilent, 10

##! Special Workspace
bind = Super, Y, togglespecialworkspace, youtube
bind = Super SHIFT, Y, movetoworkspacesilent, special:youtube
bind = Super, T, togglespecialworkspace, todo
bind = Super SHIFT, T, movetoworkspacesilent, special:todo
bind = Super, P, togglespecialworkspace, temp
bind = Super SHIFT, P, movetoworkspacesilent, special:temp
